version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: compose/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../app:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t web